// GENERATED FILE — do not hand-edit.
// Produced by scripts/atlas/build-iso.mjs from a Wikidata SPARQL query.
// Re-run with: npm run atlas:iso
//
// This is the join table every other Atlas data source keys off of:
// ISO3 for World Bank and Wikidata queries, M49 for UN Comtrade (which
// returns numeric reporter/partner codes with null names), Wikidata Q-id
// for SPARQL lookups, and the enwiki article title for the Wikipedia
// summary API.

export interface IsoCountry {
  iso3: string
  iso2: string
  m49: string
  name: string
  qid: string
  wikiTitle: string
  region?: string
}

export const ISO_COUNTRIES: readonly IsoCountry[] = [
  { iso3: "AFG", iso2: "AF", m49: "004", name: "Afghanistan", qid: "Q889", wikiTitle: "Afghanistan", region: "Asia" },
  { iso3: "ALA", iso2: "AX", m49: "248", name: "Åland", qid: "Q5689", wikiTitle: "Åland", region: undefined },
  { iso3: "ALB", iso2: "AL", m49: "008", name: "Albania", qid: "Q222", wikiTitle: "Albania", region: "Europe" },
  { iso3: "DZA", iso2: "DZ", m49: "012", name: "Algeria", qid: "Q262", wikiTitle: "Algeria", region: "Africa" },
  { iso3: "ASM", iso2: "AS", m49: "016", name: "American Samoa", qid: "Q16641", wikiTitle: "American Samoa", region: "Insular Oceania" },
  { iso3: "AND", iso2: "AD", m49: "020", name: "Andorra", qid: "Q228", wikiTitle: "Andorra", region: "Europe" },
  { iso3: "AGO", iso2: "AO", m49: "024", name: "Angola", qid: "Q916", wikiTitle: "Angola", region: "Africa" },
  { iso3: "AIA", iso2: "AI", m49: "660", name: "Anguilla", qid: "Q25228", wikiTitle: "Anguilla", region: "North America" },
  { iso3: "ATA", iso2: "AQ", m49: "010", name: "Antarctica", qid: "Q51", wikiTitle: "Antarctica", region: "Antarctica" },
  { iso3: "ATG", iso2: "AG", m49: "028", name: "Antigua and Barbuda", qid: "Q781", wikiTitle: "Antigua and Barbuda", region: "North America" },
  { iso3: "ARG", iso2: "AR", m49: "032", name: "Argentina", qid: "Q414", wikiTitle: "Argentina", region: "South America" },
  { iso3: "ARM", iso2: "AM", m49: "051", name: "Armenia", qid: "Q399", wikiTitle: "Armenia", region: "Asia" },
  { iso3: "ABW", iso2: "AW", m49: "533", name: "Aruba", qid: "Q21203", wikiTitle: "Aruba", region: "North America" },
  { iso3: "AUS", iso2: "AU", m49: "036", name: "Australia", qid: "Q408", wikiTitle: "Australia", region: "Oceania" },
  { iso3: "AUT", iso2: "AT", m49: "040", name: "Austria", qid: "Q40", wikiTitle: "Austria", region: "Europe" },
  { iso3: "AZE", iso2: "AZ", m49: "031", name: "Azerbaijan", qid: "Q227", wikiTitle: "Azerbaijan", region: "Asia" },
  { iso3: "BHR", iso2: "BH", m49: "048", name: "Bahrain", qid: "Q398", wikiTitle: "Bahrain", region: "Asia" },
  { iso3: "BGD", iso2: "BD", m49: "050", name: "Bangladesh", qid: "Q902", wikiTitle: "Bangladesh", region: "Asia" },
  { iso3: "BRB", iso2: "BB", m49: "052", name: "Barbados", qid: "Q244", wikiTitle: "Barbados", region: "North America" },
  { iso3: "BLR", iso2: "BY", m49: "112", name: "Belarus", qid: "Q184", wikiTitle: "Belarus", region: "Europe" },
  { iso3: "BEL", iso2: "BE", m49: "056", name: "Belgium", qid: "Q31", wikiTitle: "Belgium", region: "Europe" },
  { iso3: "BLZ", iso2: "BZ", m49: "084", name: "Belize", qid: "Q242", wikiTitle: "Belize", region: "Central America" },
  { iso3: "BEN", iso2: "BJ", m49: "204", name: "Benin", qid: "Q962", wikiTitle: "Benin", region: "Africa" },
  { iso3: "BMU", iso2: "BM", m49: "060", name: "Bermuda", qid: "Q23635", wikiTitle: "Bermuda", region: "North America" },
  { iso3: "BTN", iso2: "BT", m49: "064", name: "Bhutan", qid: "Q917", wikiTitle: "Bhutan", region: "Asia" },
  { iso3: "BOL", iso2: "BO", m49: "068", name: "Bolivia", qid: "Q750", wikiTitle: "Bolivia", region: "South America" },
  { iso3: "BIH", iso2: "BA", m49: "070", name: "Bosnia and Herzegovina", qid: "Q225", wikiTitle: "Bosnia and Herzegovina", region: "Europe" },
  { iso3: "BWA", iso2: "BW", m49: "072", name: "Botswana", qid: "Q963", wikiTitle: "Botswana", region: "Africa" },
  { iso3: "BVT", iso2: "BV", m49: "074", name: "Bouvet Island", qid: "Q23408", wikiTitle: "Bouvet Island", region: "Antarctica" },
  { iso3: "BRA", iso2: "BR", m49: "076", name: "Brazil", qid: "Q155", wikiTitle: "Brazil", region: "South America" },
  { iso3: "IOT", iso2: "IO", m49: "086", name: "British Indian Ocean Territory", qid: "Q43448", wikiTitle: "British Indian Ocean Territory", region: "Africa" },
  { iso3: "VGB", iso2: "VG", m49: "092", name: "British Virgin Islands", qid: "Q25305", wikiTitle: "British Virgin Islands", region: "North America" },
  { iso3: "BRN", iso2: "BN", m49: "096", name: "Brunei", qid: "Q921", wikiTitle: "Brunei", region: "Asia" },
  { iso3: "BGR", iso2: "BG", m49: "100", name: "Bulgaria", qid: "Q219", wikiTitle: "Bulgaria", region: "Europe" },
  { iso3: "BFA", iso2: "BF", m49: "854", name: "Burkina Faso", qid: "Q965", wikiTitle: "Burkina Faso", region: "Africa" },
  { iso3: "BDI", iso2: "BI", m49: "108", name: "Burundi", qid: "Q967", wikiTitle: "Burundi", region: "Africa" },
  { iso3: "KHM", iso2: "KH", m49: "116", name: "Cambodia", qid: "Q424", wikiTitle: "Cambodia", region: "Asia" },
  { iso3: "CMR", iso2: "CM", m49: "120", name: "Cameroon", qid: "Q1009", wikiTitle: "Cameroon", region: "Africa" },
  { iso3: "CAN", iso2: "CA", m49: "124", name: "Canada", qid: "Q16", wikiTitle: "Canada", region: "North America" },
  { iso3: "CPV", iso2: "CV", m49: "132", name: "Cape Verde", qid: "Q1011", wikiTitle: "Cape Verde", region: "Africa" },
  { iso3: "BES", iso2: "BQ", m49: "535", name: "Caribbean Netherlands", qid: "Q27561", wikiTitle: "Caribbean Netherlands", region: "North America" },
  { iso3: "CYM", iso2: "KY", m49: "136", name: "Cayman Islands", qid: "Q5785", wikiTitle: "Cayman Islands", region: "North America" },
  { iso3: "CAF", iso2: "CF", m49: "140", name: "Central African Republic", qid: "Q929", wikiTitle: "Central African Republic", region: "Africa" },
  { iso3: "TCD", iso2: "TD", m49: "148", name: "Chad", qid: "Q657", wikiTitle: "Chad", region: "Africa" },
  { iso3: "CHL", iso2: "CL", m49: "152", name: "Chile", qid: "Q298", wikiTitle: "Chile", region: "South America" },
  { iso3: "CXR", iso2: "CX", m49: "162", name: "Christmas Island", qid: "Q31063", wikiTitle: "Christmas Island", region: "Asia" },
  { iso3: "CCK", iso2: "CC", m49: "166", name: "Cocos (Keeling) Islands", qid: "Q36004", wikiTitle: "Cocos (Keeling) Islands", region: "Oceania" },
  { iso3: "COL", iso2: "CO", m49: "170", name: "Colombia", qid: "Q739", wikiTitle: "Colombia", region: "South America" },
  { iso3: "COM", iso2: "KM", m49: "174", name: "Comoros", qid: "Q970", wikiTitle: "Comoros", region: "Africa" },
  { iso3: "COK", iso2: "CK", m49: "184", name: "Cook Islands", qid: "Q26988", wikiTitle: "Cook Islands", region: "Insular Oceania" },
  { iso3: "CRI", iso2: "CR", m49: "188", name: "Costa Rica", qid: "Q800", wikiTitle: "Costa Rica", region: "North America" },
  { iso3: "HRV", iso2: "HR", m49: "191", name: "Croatia", qid: "Q224", wikiTitle: "Croatia", region: "Europe" },
  { iso3: "CUB", iso2: "CU", m49: "192", name: "Cuba", qid: "Q241", wikiTitle: "Cuba", region: "North America" },
  { iso3: "CUW", iso2: "CW", m49: "531", name: "Curaçao", qid: "Q25279", wikiTitle: "Curaçao", region: "North America" },
  { iso3: "CYP", iso2: "CY", m49: "196", name: "Cyprus", qid: "Q229", wikiTitle: "Cyprus", region: "Europe" },
  { iso3: "CZE", iso2: "CZ", m49: "203", name: "Czech Republic", qid: "Q213", wikiTitle: "Czech Republic", region: "Europe" },
  { iso3: "COD", iso2: "CD", m49: "180", name: "Democratic Republic of the Congo", qid: "Q974", wikiTitle: "Democratic Republic of the Congo", region: "Africa" },
  { iso3: "DNK", iso2: "DK", m49: "208", name: "Denmark", qid: "Q35", wikiTitle: "Denmark", region: "Europe" },
  { iso3: "DJI", iso2: "DJ", m49: "262", name: "Djibouti", qid: "Q977", wikiTitle: "Djibouti", region: "Africa" },
  { iso3: "DMA", iso2: "DM", m49: "212", name: "Dominica", qid: "Q784", wikiTitle: "Dominica", region: "North America" },
  { iso3: "DOM", iso2: "DO", m49: "214", name: "Dominican Republic", qid: "Q786", wikiTitle: "Dominican Republic", region: "North America" },
  { iso3: "ECU", iso2: "EC", m49: "218", name: "Ecuador", qid: "Q736", wikiTitle: "Ecuador", region: "South America" },
  { iso3: "EGY", iso2: "EG", m49: "818", name: "Egypt", qid: "Q79", wikiTitle: "Egypt", region: "Africa" },
  { iso3: "SLV", iso2: "SV", m49: "222", name: "El Salvador", qid: "Q792", wikiTitle: "El Salvador", region: "North America" },
  { iso3: "GNQ", iso2: "GQ", m49: "226", name: "Equatorial Guinea", qid: "Q983", wikiTitle: "Equatorial Guinea", region: "Africa" },
  { iso3: "ERI", iso2: "ER", m49: "232", name: "Eritrea", qid: "Q986", wikiTitle: "Eritrea", region: "Africa" },
  { iso3: "EST", iso2: "EE", m49: "233", name: "Estonia", qid: "Q191", wikiTitle: "Estonia", region: "Europe" },
  { iso3: "SWZ", iso2: "SZ", m49: "748", name: "Eswatini", qid: "Q1050", wikiTitle: "Eswatini", region: "Africa" },
  { iso3: "ETH", iso2: "ET", m49: "231", name: "Ethiopia", qid: "Q115", wikiTitle: "Ethiopia", region: "Africa" },
  { iso3: "FLK", iso2: "FK", m49: "238", name: "Falkland Islands", qid: "Q9648", wikiTitle: "Falkland Islands", region: "South America" },
  { iso3: "FRO", iso2: "FO", m49: "234", name: "Faroe Islands", qid: "Q4628", wikiTitle: "Faroe Islands", region: "Europe" },
  { iso3: "FSM", iso2: "FM", m49: "583", name: "Federated States of Micronesia", qid: "Q702", wikiTitle: "Federated States of Micronesia", region: "Oceania" },
  { iso3: "FJI", iso2: "FJ", m49: "242", name: "Fiji", qid: "Q712", wikiTitle: "Fiji", region: "Insular Oceania" },
  { iso3: "FIN", iso2: "FI", m49: "246", name: "Finland", qid: "Q33", wikiTitle: "Finland", region: "Europe" },
  { iso3: "FRA", iso2: "FR", m49: "250", name: "France", qid: "Q142", wikiTitle: "France", region: "Europe" },
  { iso3: "GUF", iso2: "GF", m49: "254", name: "French Guiana", qid: "Q3769", wikiTitle: "French Guiana", region: "South America" },
  { iso3: "PYF", iso2: "PF", m49: "258", name: "French Polynesia", qid: "Q30971", wikiTitle: "French Polynesia", region: "Insular Oceania" },
  { iso3: "ATF", iso2: "TF", m49: "260", name: "French Southern and Antarctic Lands", qid: "Q129003", wikiTitle: "French Southern and Antarctic Lands", region: "Antarctica" },
  { iso3: "GAB", iso2: "GA", m49: "266", name: "Gabon", qid: "Q1000", wikiTitle: "Gabon", region: "Africa" },
  { iso3: "GEO", iso2: "GE", m49: "268", name: "Georgia", qid: "Q230", wikiTitle: "Georgia (country)", region: "Europe" },
  { iso3: "DEU", iso2: "DE", m49: "276", name: "Germany", qid: "Q183", wikiTitle: "Germany", region: "Europe" },
  { iso3: "GHA", iso2: "GH", m49: "288", name: "Ghana", qid: "Q117", wikiTitle: "Ghana", region: "Africa" },
  { iso3: "GIB", iso2: "GI", m49: "292", name: "Gibraltar", qid: "Q1410", wikiTitle: "Gibraltar", region: "Europe" },
  { iso3: "GRC", iso2: "GR", m49: "300", name: "Greece", qid: "Q41", wikiTitle: "Greece", region: "Europe" },
  { iso3: "GRL", iso2: "GL", m49: "304", name: "Greenland", qid: "Q223", wikiTitle: "Greenland", region: "North America" },
  { iso3: "GRD", iso2: "GD", m49: "308", name: "Grenada", qid: "Q769", wikiTitle: "Grenada", region: "North America" },
  { iso3: "GLP", iso2: "GP", m49: "312", name: "Guadeloupe", qid: "Q17012", wikiTitle: "Guadeloupe", region: "North America" },
  { iso3: "GUM", iso2: "GU", m49: "316", name: "Guam", qid: "Q16635", wikiTitle: "Guam", region: "Oceania" },
  { iso3: "GTM", iso2: "GT", m49: "320", name: "Guatemala", qid: "Q774", wikiTitle: "Guatemala", region: "North America" },
  { iso3: "GGY", iso2: "GG", m49: "831", name: "Guernsey", qid: "Q25230", wikiTitle: "Bailiwick of Guernsey", region: "Europe" },
  { iso3: "GIN", iso2: "GN", m49: "324", name: "Guinea", qid: "Q1006", wikiTitle: "Guinea", region: "Africa" },
  { iso3: "GNB", iso2: "GW", m49: "624", name: "Guinea-Bissau", qid: "Q1007", wikiTitle: "Guinea-Bissau", region: "Africa" },
  { iso3: "GUY", iso2: "GY", m49: "328", name: "Guyana", qid: "Q734", wikiTitle: "Guyana", region: "South America" },
  { iso3: "HTI", iso2: "HT", m49: "332", name: "Haiti", qid: "Q790", wikiTitle: "Haiti", region: "North America" },
  { iso3: "HMD", iso2: "HM", m49: "334", name: "Heard Island and McDonald Islands", qid: "Q131198", wikiTitle: "Heard Island and McDonald Islands", region: "Antarctica" },
  { iso3: "HND", iso2: "HN", m49: "340", name: "Honduras", qid: "Q783", wikiTitle: "Honduras", region: "North America" },
  { iso3: "HKG", iso2: "HK", m49: "344", name: "Hong Kong", qid: "Q8646", wikiTitle: "Hong Kong", region: "Asia" },
  { iso3: "HUN", iso2: "HU", m49: "348", name: "Hungary", qid: "Q28", wikiTitle: "Hungary", region: "Europe" },
  { iso3: "ISL", iso2: "IS", m49: "352", name: "Iceland", qid: "Q189", wikiTitle: "Iceland", region: "Europe" },
  { iso3: "IND", iso2: "IN", m49: "356", name: "India", qid: "Q668", wikiTitle: "India", region: "Asia" },
  { iso3: "IDN", iso2: "ID", m49: "360", name: "Indonesia", qid: "Q252", wikiTitle: "Indonesia", region: "Asia" },
  { iso3: "IRN", iso2: "IR", m49: "364", name: "Iran", qid: "Q794", wikiTitle: "Iran", region: "Asia" },
  { iso3: "IRQ", iso2: "IQ", m49: "368", name: "Iraq", qid: "Q796", wikiTitle: "Iraq", region: "Asia" },
  { iso3: "IRL", iso2: "IE", m49: "372", name: "Ireland", qid: "Q27", wikiTitle: "Republic of Ireland", region: "Europe" },
  { iso3: "IMN", iso2: "IM", m49: "833", name: "Isle of Man", qid: "Q9676", wikiTitle: "Isle of Man", region: "Europe" },
  { iso3: "ISR", iso2: "IL", m49: "376", name: "Israel", qid: "Q801", wikiTitle: "Israel", region: "Asia" },
  { iso3: "ITA", iso2: "IT", m49: "380", name: "Italy", qid: "Q38", wikiTitle: "Italy", region: "Europe" },
  { iso3: "CIV", iso2: "CI", m49: "384", name: "Ivory Coast", qid: "Q1008", wikiTitle: "Ivory Coast", region: "Africa" },
  { iso3: "JAM", iso2: "JM", m49: "388", name: "Jamaica", qid: "Q766", wikiTitle: "Jamaica", region: "North America" },
  { iso3: "JPN", iso2: "JP", m49: "392", name: "Japan", qid: "Q17", wikiTitle: "Japan", region: "Asia" },
  { iso3: "JEY", iso2: "JE", m49: "832", name: "Jersey", qid: "Q785", wikiTitle: "Jersey", region: "Europe" },
  { iso3: "JOR", iso2: "JO", m49: "400", name: "Jordan", qid: "Q810", wikiTitle: "Jordan", region: "Asia" },
  { iso3: "KAZ", iso2: "KZ", m49: "398", name: "Kazakhstan", qid: "Q232", wikiTitle: "Kazakhstan", region: "Asia" },
  { iso3: "KEN", iso2: "KE", m49: "404", name: "Kenya", qid: "Q114", wikiTitle: "Kenya", region: "Africa" },
  { iso3: "NLD", iso2: "NL", m49: "528", name: "Kingdom of the Netherlands", qid: "Q29999", wikiTitle: "Kingdom of the Netherlands", region: "Europe" },
  { iso3: "KIR", iso2: "KI", m49: "296", name: "Kiribati", qid: "Q710", wikiTitle: "Kiribati", region: "Oceania" },
  { iso3: "XKX", iso2: "XK", m49: "", name: "Kosovo", qid: "Q1246", wikiTitle: "Kosovo", region: "Europe" },
  { iso3: "KWT", iso2: "KW", m49: "414", name: "Kuwait", qid: "Q817", wikiTitle: "Kuwait", region: "Asia" },
  { iso3: "KGZ", iso2: "KG", m49: "417", name: "Kyrgyzstan", qid: "Q813", wikiTitle: "Kyrgyzstan", region: "Asia" },
  { iso3: "LAO", iso2: "LA", m49: "418", name: "Laos", qid: "Q819", wikiTitle: "Laos", region: "Asia" },
  { iso3: "LVA", iso2: "LV", m49: "428", name: "Latvia", qid: "Q211", wikiTitle: "Latvia", region: "Europe" },
  { iso3: "LBN", iso2: "LB", m49: "422", name: "Lebanon", qid: "Q822", wikiTitle: "Lebanon", region: "Asia" },
  { iso3: "LSO", iso2: "LS", m49: "426", name: "Lesotho", qid: "Q1013", wikiTitle: "Lesotho", region: "Africa" },
  { iso3: "LBR", iso2: "LR", m49: "430", name: "Liberia", qid: "Q1014", wikiTitle: "Liberia", region: "Africa" },
  { iso3: "LBY", iso2: "LY", m49: "434", name: "Libya", qid: "Q1016", wikiTitle: "Libya", region: "Africa" },
  { iso3: "LIE", iso2: "LI", m49: "438", name: "Liechtenstein", qid: "Q347", wikiTitle: "Liechtenstein", region: "Europe" },
  { iso3: "LTU", iso2: "LT", m49: "440", name: "Lithuania", qid: "Q37", wikiTitle: "Lithuania", region: "Europe" },
  { iso3: "LUX", iso2: "LU", m49: "442", name: "Luxembourg", qid: "Q32", wikiTitle: "Luxembourg", region: "Europe" },
  { iso3: "MAC", iso2: "MO", m49: "446", name: "Macau", qid: "Q14773", wikiTitle: "Macau", region: "Asia" },
  { iso3: "MDG", iso2: "MG", m49: "450", name: "Madagascar", qid: "Q1019", wikiTitle: "Madagascar", region: "Africa" },
  { iso3: "MWI", iso2: "MW", m49: "454", name: "Malawi", qid: "Q1020", wikiTitle: "Malawi", region: "Africa" },
  { iso3: "MYS", iso2: "MY", m49: "458", name: "Malaysia", qid: "Q833", wikiTitle: "Malaysia", region: "Asia" },
  { iso3: "MDV", iso2: "MV", m49: "462", name: "Maldives", qid: "Q826", wikiTitle: "Maldives", region: "Asia" },
  { iso3: "MLI", iso2: "ML", m49: "466", name: "Mali", qid: "Q912", wikiTitle: "Mali", region: "Africa" },
  { iso3: "MLT", iso2: "MT", m49: "470", name: "Malta", qid: "Q233", wikiTitle: "Malta", region: "Europe" },
  { iso3: "MHL", iso2: "MH", m49: "584", name: "Marshall Islands", qid: "Q709", wikiTitle: "Marshall Islands", region: "Oceania" },
  { iso3: "MTQ", iso2: "MQ", m49: "474", name: "Martinique", qid: "Q17054", wikiTitle: "Martinique", region: "North America" },
  { iso3: "MRT", iso2: "MR", m49: "478", name: "Mauritania", qid: "Q1025", wikiTitle: "Mauritania", region: "Africa" },
  { iso3: "MUS", iso2: "MU", m49: "480", name: "Mauritius", qid: "Q1027", wikiTitle: "Mauritius", region: "Africa" },
  { iso3: "MYT", iso2: "YT", m49: "175", name: "Mayotte", qid: "Q17063", wikiTitle: "Mayotte", region: "Africa" },
  { iso3: "MEX", iso2: "MX", m49: "484", name: "Mexico", qid: "Q96", wikiTitle: "Mexico", region: "North America" },
  { iso3: "MDA", iso2: "MD", m49: "498", name: "Moldova", qid: "Q217", wikiTitle: "Moldova", region: "Europe" },
  { iso3: "MCO", iso2: "MC", m49: "492", name: "Monaco", qid: "Q235", wikiTitle: "Monaco", region: "Europe" },
  { iso3: "MNG", iso2: "MN", m49: "496", name: "Mongolia", qid: "Q711", wikiTitle: "Mongolia", region: "Asia" },
  { iso3: "MNE", iso2: "ME", m49: "499", name: "Montenegro", qid: "Q236", wikiTitle: "Montenegro", region: "Europe" },
  { iso3: "MSR", iso2: "MS", m49: "500", name: "Montserrat", qid: "Q13353", wikiTitle: "Montserrat", region: "North America" },
  { iso3: "MAR", iso2: "MA", m49: "504", name: "Morocco", qid: "Q1028", wikiTitle: "Morocco", region: "Africa" },
  { iso3: "MOZ", iso2: "MZ", m49: "508", name: "Mozambique", qid: "Q1029", wikiTitle: "Mozambique", region: "Africa" },
  { iso3: "MMR", iso2: "MM", m49: "104", name: "Myanmar", qid: "Q836", wikiTitle: "Myanmar", region: "Asia" },
  { iso3: "NAM", iso2: "NA", m49: "516", name: "Namibia", qid: "Q1030", wikiTitle: "Namibia", region: "Africa" },
  { iso3: "NRU", iso2: "NR", m49: "520", name: "Nauru", qid: "Q697", wikiTitle: "Nauru", region: "Oceania" },
  { iso3: "NPL", iso2: "NP", m49: "524", name: "Nepal", qid: "Q837", wikiTitle: "Nepal", region: "Asia" },
  { iso3: "NCL", iso2: "NC", m49: "540", name: "New Caledonia", qid: "Q33788", wikiTitle: "New Caledonia", region: "Insular Oceania" },
  { iso3: "NZL", iso2: "NZ", m49: "554", name: "New Zealand", qid: "Q664", wikiTitle: "New Zealand", region: "Oceania" },
  { iso3: "NIC", iso2: "NI", m49: "558", name: "Nicaragua", qid: "Q811", wikiTitle: "Nicaragua", region: "North America" },
  { iso3: "NER", iso2: "NE", m49: "562", name: "Niger", qid: "Q1032", wikiTitle: "Niger", region: "Africa" },
  { iso3: "NGA", iso2: "NG", m49: "566", name: "Nigeria", qid: "Q1033", wikiTitle: "Nigeria", region: "Africa" },
  { iso3: "NIU", iso2: "NU", m49: "570", name: "Niue", qid: "Q34020", wikiTitle: "Niue", region: "Insular Oceania" },
  { iso3: "NFK", iso2: "NF", m49: "574", name: "Norfolk Island", qid: "Q31057", wikiTitle: "Norfolk Island", region: "Insular Oceania" },
  { iso3: "PRK", iso2: "KP", m49: "408", name: "North Korea", qid: "Q423", wikiTitle: "North Korea", region: "Asia" },
  { iso3: "MKD", iso2: "MK", m49: "807", name: "North Macedonia", qid: "Q221", wikiTitle: "North Macedonia", region: "Europe" },
  { iso3: "MNP", iso2: "MP", m49: "580", name: "Northern Mariana Islands", qid: "Q16644", wikiTitle: "Northern Mariana Islands", region: "Insular Oceania" },
  { iso3: "NOR", iso2: "NO", m49: "578", name: "Norway", qid: "Q20", wikiTitle: "Norway", region: "Europe" },
  { iso3: "OMN", iso2: "OM", m49: "512", name: "Oman", qid: "Q842", wikiTitle: "Oman", region: "Asia" },
  { iso3: "PAK", iso2: "PK", m49: "586", name: "Pakistan", qid: "Q843", wikiTitle: "Pakistan", region: "Asia" },
  { iso3: "PLW", iso2: "PW", m49: "585", name: "Palau", qid: "Q695", wikiTitle: "Palau", region: "Oceania" },
  { iso3: "PSE", iso2: "PS", m49: "275", name: "Palestine", qid: "Q219060", wikiTitle: "Palestine", region: "Asia" },
  { iso3: "PAN", iso2: "PA", m49: "591", name: "Panama", qid: "Q804", wikiTitle: "Panama", region: "North America" },
  { iso3: "PNG", iso2: "PG", m49: "598", name: "Papua New Guinea", qid: "Q691", wikiTitle: "Papua New Guinea", region: "Oceania" },
  { iso3: "PRY", iso2: "PY", m49: "600", name: "Paraguay", qid: "Q733", wikiTitle: "Paraguay", region: "South America" },
  { iso3: "CHN", iso2: "CN", m49: "156", name: "People's Republic of China", qid: "Q148", wikiTitle: "China", region: "Asia" },
  { iso3: "PER", iso2: "PE", m49: "604", name: "Peru", qid: "Q419", wikiTitle: "Peru", region: "South America" },
  { iso3: "PHL", iso2: "PH", m49: "608", name: "Philippines", qid: "Q928", wikiTitle: "Philippines", region: "Asia" },
  { iso3: "PCN", iso2: "PN", m49: "612", name: "Pitcairn Islands", qid: "Q35672", wikiTitle: "Pitcairn Islands", region: "Insular Oceania" },
  { iso3: "POL", iso2: "PL", m49: "616", name: "Poland", qid: "Q36", wikiTitle: "Poland", region: "Europe" },
  { iso3: "PRT", iso2: "PT", m49: "620", name: "Portugal", qid: "Q45", wikiTitle: "Portugal", region: "Europe" },
  { iso3: "PRI", iso2: "PR", m49: "630", name: "Puerto Rico", qid: "Q1183", wikiTitle: "Puerto Rico", region: "North America" },
  { iso3: "QAT", iso2: "QA", m49: "634", name: "Qatar", qid: "Q846", wikiTitle: "Qatar", region: "Asia" },
  { iso3: "COG", iso2: "CG", m49: "178", name: "Republic of the Congo", qid: "Q971", wikiTitle: "Republic of the Congo", region: "Africa" },
  { iso3: "REU", iso2: "RE", m49: "638", name: "Réunion", qid: "Q17070", wikiTitle: "Réunion", region: "Africa" },
  { iso3: "ROU", iso2: "RO", m49: "642", name: "Romania", qid: "Q218", wikiTitle: "Romania", region: "Europe" },
  { iso3: "RUS", iso2: "RU", m49: "643", name: "Russia", qid: "Q159", wikiTitle: "Russia", region: "Eurasia" },
  { iso3: "RWA", iso2: "RW", m49: "646", name: "Rwanda", qid: "Q1037", wikiTitle: "Rwanda", region: "Africa" },
  { iso3: "BLM", iso2: "BL", m49: "652", name: "Saint Barthélemy", qid: "Q25362", wikiTitle: "Saint Barthélemy", region: "North America" },
  { iso3: "SHN", iso2: "SH", m49: "654", name: "Saint Helena, Ascension and Tristan da Cunha", qid: "Q192184", wikiTitle: "Saint Helena, Ascension and Tristan da Cunha", region: "Africa" },
  { iso3: "KNA", iso2: "KN", m49: "659", name: "Saint Kitts and Nevis", qid: "Q763", wikiTitle: "Saint Kitts and Nevis", region: "North America" },
  { iso3: "LCA", iso2: "LC", m49: "662", name: "Saint Lucia", qid: "Q760", wikiTitle: "Saint Lucia", region: "North America" },
  { iso3: "SPM", iso2: "PM", m49: "666", name: "Saint Pierre and Miquelon", qid: "Q34617", wikiTitle: "Saint Pierre and Miquelon", region: "North America" },
  { iso3: "VCT", iso2: "VC", m49: "670", name: "Saint Vincent and the Grenadines", qid: "Q757", wikiTitle: "Saint Vincent and the Grenadines", region: "North America" },
  { iso3: "MAF", iso2: "MF", m49: "663", name: "Saint-Martin", qid: "Q126125", wikiTitle: "Collectivity of Saint Martin", region: "North America" },
  { iso3: "WSM", iso2: "WS", m49: "882", name: "Samoa", qid: "Q683", wikiTitle: "Samoa", region: "Oceania" },
  { iso3: "SMR", iso2: "SM", m49: "674", name: "San Marino", qid: "Q238", wikiTitle: "San Marino", region: "Europe" },
  { iso3: "STP", iso2: "ST", m49: "678", name: "São Tomé and Príncipe", qid: "Q1039", wikiTitle: "São Tomé and Príncipe", region: "Africa" },
  { iso3: "SAU", iso2: "SA", m49: "682", name: "Saudi Arabia", qid: "Q851", wikiTitle: "Saudi Arabia", region: "Asia" },
  { iso3: "SEN", iso2: "SN", m49: "686", name: "Senegal", qid: "Q1041", wikiTitle: "Senegal", region: "Africa" },
  { iso3: "SRB", iso2: "RS", m49: "688", name: "Serbia", qid: "Q403", wikiTitle: "Serbia", region: "Europe" },
  { iso3: "SYC", iso2: "SC", m49: "690", name: "Seychelles", qid: "Q1042", wikiTitle: "Seychelles", region: "Africa" },
  { iso3: "SLE", iso2: "SL", m49: "694", name: "Sierra Leone", qid: "Q1044", wikiTitle: "Sierra Leone", region: "Africa" },
  { iso3: "SGP", iso2: "SG", m49: "702", name: "Singapore", qid: "Q334", wikiTitle: "Singapore", region: "Asia" },
  { iso3: "SXM", iso2: "SX", m49: "534", name: "Sint Maarten", qid: "Q26273", wikiTitle: "Sint Maarten", region: "North America" },
  { iso3: "SVK", iso2: "SK", m49: "703", name: "Slovakia", qid: "Q214", wikiTitle: "Slovakia", region: "Europe" },
  { iso3: "SVN", iso2: "SI", m49: "705", name: "Slovenia", qid: "Q215", wikiTitle: "Slovenia", region: "Europe" },
  { iso3: "SLB", iso2: "SB", m49: "090", name: "Solomon Islands", qid: "Q685", wikiTitle: "Solomon Islands", region: "Oceania" },
  { iso3: "SOM", iso2: "SO", m49: "706", name: "Somalia", qid: "Q1045", wikiTitle: "Somalia", region: "Africa" },
  { iso3: "ZAF", iso2: "ZA", m49: "710", name: "South Africa", qid: "Q258", wikiTitle: "South Africa", region: "Africa" },
  { iso3: "SGS", iso2: "GS", m49: "239", name: "South Georgia and the South Sandwich Islands", qid: "Q35086", wikiTitle: "South Georgia and the South Sandwich Islands", region: "South America" },
  { iso3: "KOR", iso2: "KR", m49: "410", name: "South Korea", qid: "Q884", wikiTitle: "South Korea", region: "Asia" },
  { iso3: "SSD", iso2: "SS", m49: "728", name: "South Sudan", qid: "Q958", wikiTitle: "South Sudan", region: "Africa" },
  { iso3: "ESP", iso2: "ES", m49: "724", name: "Spain", qid: "Q29", wikiTitle: "Spain", region: "Europe" },
  { iso3: "LKA", iso2: "LK", m49: "144", name: "Sri Lanka", qid: "Q854", wikiTitle: "Sri Lanka", region: "Asia" },
  { iso3: "SDN", iso2: "SD", m49: "729", name: "Sudan", qid: "Q1049", wikiTitle: "Sudan", region: "Africa" },
  { iso3: "SUR", iso2: "SR", m49: "740", name: "Suriname", qid: "Q730", wikiTitle: "Suriname", region: "South America" },
  { iso3: "SJM", iso2: "SJ", m49: "744", name: "Svalbard and Jan Mayen", qid: "Q842829", wikiTitle: "Svalbard and Jan Mayen", region: "Europe" },
  { iso3: "SWE", iso2: "SE", m49: "752", name: "Sweden", qid: "Q34", wikiTitle: "Sweden", region: "Europe" },
  { iso3: "CHE", iso2: "CH", m49: "756", name: "Switzerland", qid: "Q39", wikiTitle: "Switzerland", region: "Europe" },
  { iso3: "SYR", iso2: "SY", m49: "760", name: "Syria", qid: "Q858", wikiTitle: "Syria", region: "Asia" },
  { iso3: "TWN", iso2: "TW", m49: "158", name: "Taiwan", qid: "Q865", wikiTitle: "Taiwan", region: "Asia" },
  { iso3: "TJK", iso2: "TJ", m49: "762", name: "Tajikistan", qid: "Q863", wikiTitle: "Tajikistan", region: "Asia" },
  { iso3: "TZA", iso2: "TZ", m49: "834", name: "Tanzania", qid: "Q924", wikiTitle: "Tanzania", region: "Africa" },
  { iso3: "THA", iso2: "TH", m49: "764", name: "Thailand", qid: "Q869", wikiTitle: "Thailand", region: "Asia" },
  { iso3: "BHS", iso2: "BS", m49: "044", name: "The Bahamas", qid: "Q778", wikiTitle: "The Bahamas", region: "North America" },
  { iso3: "GMB", iso2: "GM", m49: "270", name: "The Gambia", qid: "Q1005", wikiTitle: "The Gambia", region: "Africa" },
  { iso3: "TLS", iso2: "TL", m49: "626", name: "Timor-Leste", qid: "Q574", wikiTitle: "Timor-Leste", region: "Asia" },
  { iso3: "TGO", iso2: "TG", m49: "768", name: "Togo", qid: "Q945", wikiTitle: "Togo", region: "Africa" },
  { iso3: "TKL", iso2: "TK", m49: "772", name: "Tokelau", qid: "Q36823", wikiTitle: "Tokelau", region: "Insular Oceania" },
  { iso3: "TON", iso2: "TO", m49: "776", name: "Tonga", qid: "Q678", wikiTitle: "Tonga", region: "Oceania" },
  { iso3: "TTO", iso2: "TT", m49: "780", name: "Trinidad and Tobago", qid: "Q754", wikiTitle: "Trinidad and Tobago", region: "North America" },
  { iso3: "TUN", iso2: "TN", m49: "788", name: "Tunisia", qid: "Q948", wikiTitle: "Tunisia", region: "Africa" },
  { iso3: "TUR", iso2: "TR", m49: "792", name: "Turkey", qid: "Q43", wikiTitle: "Turkey", region: "Asia" },
  { iso3: "TKM", iso2: "TM", m49: "795", name: "Turkmenistan", qid: "Q874", wikiTitle: "Turkmenistan", region: "Asia" },
  { iso3: "TCA", iso2: "TC", m49: "796", name: "Turks and Caicos Islands", qid: "Q18221", wikiTitle: "Turks and Caicos Islands", region: "North America" },
  { iso3: "TUV", iso2: "TV", m49: "798", name: "Tuvalu", qid: "Q672", wikiTitle: "Tuvalu", region: "Oceania" },
  { iso3: "UGA", iso2: "UG", m49: "800", name: "Uganda", qid: "Q1036", wikiTitle: "Uganda", region: "Africa" },
  { iso3: "UKR", iso2: "UA", m49: "804", name: "Ukraine", qid: "Q212", wikiTitle: "Ukraine", region: "Europe" },
  { iso3: "ARE", iso2: "AE", m49: "784", name: "United Arab Emirates", qid: "Q878", wikiTitle: "United Arab Emirates", region: "Asia" },
  { iso3: "GBR", iso2: "GB", m49: "826", name: "United Kingdom", qid: "Q145", wikiTitle: "United Kingdom", region: "Europe" },
  { iso3: "USA", iso2: "US", m49: "840", name: "United States", qid: "Q30", wikiTitle: "United States", region: "North America" },
  { iso3: "UMI", iso2: "UM", m49: "581", name: "United States Minor Outlying Islands", qid: "Q16645", wikiTitle: "United States Minor Outlying Islands", region: "Insular Oceania" },
  { iso3: "VIR", iso2: "VI", m49: "850", name: "United States Virgin Islands", qid: "Q11703", wikiTitle: "United States Virgin Islands", region: "North America" },
  { iso3: "URY", iso2: "UY", m49: "858", name: "Uruguay", qid: "Q77", wikiTitle: "Uruguay", region: "South America" },
  { iso3: "UZB", iso2: "UZ", m49: "860", name: "Uzbekistan", qid: "Q265", wikiTitle: "Uzbekistan", region: "Asia" },
  { iso3: "VUT", iso2: "VU", m49: "548", name: "Vanuatu", qid: "Q686", wikiTitle: "Vanuatu", region: "Insular Oceania" },
  { iso3: "VAT", iso2: "VA", m49: "336", name: "Vatican City", qid: "Q237", wikiTitle: "Vatican City", region: "Europe" },
  { iso3: "VEN", iso2: "VE", m49: "862", name: "Venezuela", qid: "Q717", wikiTitle: "Venezuela", region: "South America" },
  { iso3: "VNM", iso2: "VN", m49: "704", name: "Vietnam", qid: "Q881", wikiTitle: "Vietnam", region: "Asia" },
  { iso3: "WLF", iso2: "WF", m49: "876", name: "Wallis and Futuna", qid: "Q35555", wikiTitle: "Wallis and Futuna", region: "Insular Oceania" },
  { iso3: "ESH", iso2: "EH", m49: "732", name: "Western Sahara", qid: "Q6250", wikiTitle: "Western Sahara", region: "Africa" },
  { iso3: "YEM", iso2: "YE", m49: "887", name: "Yemen", qid: "Q805", wikiTitle: "Yemen", region: "Asia" },
  { iso3: "ZMB", iso2: "ZM", m49: "894", name: "Zambia", qid: "Q953", wikiTitle: "Zambia", region: "Africa" },
  { iso3: "ZWE", iso2: "ZW", m49: "716", name: "Zimbabwe", qid: "Q954", wikiTitle: "Zimbabwe", region: "Africa" },
]

export const BY_ISO3: Readonly<Record<string, IsoCountry>> = Object.fromEntries(
  ISO_COUNTRIES.map((c) => [c.iso3, c])
)

// UN Comtrade returns M49 numeric reporter/partner codes with null names —
// this is the join. Not every country has an M49 (e.g. Kosovo, XKX, is not
// a UN member and has none), so this map is intentionally sparse.
export const BY_M49: Readonly<Record<string, IsoCountry>> = Object.fromEntries(
  ISO_COUNTRIES.filter((c) => c.m49).map((c) => [c.m49, c])
)
