// Real land borders — every unordered ISO3 pair that actually shares a land
// boundary, including a handful of dependent-territory ones a quiz question
// would otherwise miss (GIB-ESP, GUF-SUR, MAF-SXM).
//
// WHY THIS EXISTS
//
// Wikidata's P47 ("shares border with"), the source
// lib/atlas/sources/wikidata.ts's fetchNeighbours pulls from, is broader
// than a land border. It also carries maritime and disputed relationships —
// "Maldives shares a border with United Kingdom" (the Chagos Archipelago
// dispute), "Kiribati shares a border with United States" (a shared claim
// over a Pacific atoll), "Sudan shares a border with Uganda" (true before
// South Sudan split off in 2011, false since). None of that is a Wikidata
// mistake — P47's own documentation covers maritime borders too — it's the
// wrong property for a "these two countries are next to each other on land"
// quiz clue.
//
// Checked directly against query.wikidata.org (2026-08-08): no qualifier on
// any country's P47 statement distinguishes land from maritime. Sampled
// Maldives-UK specifically and swept every qualifier property used on any
// P47 statement anywhere — start/end date, statement length, a handful of
// single-use ones — none of them mark border type. So there is no way to
// filter P47 by asking Wikidata a sharper question; a second, independent
// reference is the only fix that doesn't wait on hand-verifying ~450 pairs.
//
// This table is that reference: land-border pairs from mledoze/countries
// (github.com/mledoze/countries)'s `borders` field, which descends from the
// CIA World Factbook — the same data restcountries.com serves — captured
// 2026-08-08. Kosovo (mledoze's code "UNK") is remapped to this repo's XKX.
// Only pairs where both ISO3s are in lib/atlas/iso-countries.ts are kept.
//
// build-deck.mjs's buildCountry() uses this to filter, never to add: a
// Wikidata-sourced neighbour survives into deck.json only if it's also
// here. It's deliberately the full ~325-pair world table, not trimmed down
// to just the ~450 pairs the current snapshot happens to assert — so a
// true border the snapshot is missing today (Norway-Russia isn't in any
// committed snapshot's P47 result, but is a real, short land border, and is
// in this table) still works the day the snapshot catches up, without
// anyone having to touch this file again.
//
// One hand-verified correction on top of mledoze: its `borders` field lists
// IND-LKA (India-Sri Lanka) as a land border. Sri Lanka is an island — the
// Palk Strait separates it from India, no land crossing exists — so that
// pair is deliberately left out below rather than carried over. Everything
// else here is mledoze's data unmodified; re-check this table by hand
// before trusting a new pair that looks similarly implausible.
const RAW_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["AFG", "CHN"],
  ["AFG", "IRN"],
  ["AFG", "PAK"],
  ["AFG", "TJK"],
  ["AFG", "TKM"],
  ["AFG", "UZB"],
  ["AGO", "COD"],
  ["AGO", "COG"],
  ["AGO", "NAM"],
  ["AGO", "ZMB"],
  ["ALB", "GRC"],
  ["ALB", "MKD"],
  ["ALB", "MNE"],
  ["ALB", "XKX"],
  ["AND", "ESP"],
  ["AND", "FRA"],
  ["ARE", "OMN"],
  ["ARE", "SAU"],
  ["ARG", "BOL"],
  ["ARG", "BRA"],
  ["ARG", "CHL"],
  ["ARG", "PRY"],
  ["ARG", "URY"],
  ["ARM", "AZE"],
  ["ARM", "GEO"],
  ["ARM", "IRN"],
  ["ARM", "TUR"],
  ["AUT", "CHE"],
  ["AUT", "CZE"],
  ["AUT", "DEU"],
  ["AUT", "HUN"],
  ["AUT", "ITA"],
  ["AUT", "LIE"],
  ["AUT", "SVK"],
  ["AUT", "SVN"],
  ["AZE", "GEO"],
  ["AZE", "IRN"],
  ["AZE", "RUS"],
  ["AZE", "TUR"],
  ["BDI", "COD"],
  ["BDI", "RWA"],
  ["BDI", "TZA"],
  ["BEL", "DEU"],
  ["BEL", "FRA"],
  ["BEL", "LUX"],
  ["BEL", "NLD"],
  ["BEN", "BFA"],
  ["BEN", "NER"],
  ["BEN", "NGA"],
  ["BEN", "TGO"],
  ["BFA", "CIV"],
  ["BFA", "GHA"],
  ["BFA", "MLI"],
  ["BFA", "NER"],
  ["BFA", "TGO"],
  ["BGD", "IND"],
  ["BGD", "MMR"],
  ["BGR", "GRC"],
  ["BGR", "MKD"],
  ["BGR", "ROU"],
  ["BGR", "SRB"],
  ["BGR", "TUR"],
  ["BIH", "HRV"],
  ["BIH", "MNE"],
  ["BIH", "SRB"],
  ["BLR", "LTU"],
  ["BLR", "LVA"],
  ["BLR", "POL"],
  ["BLR", "RUS"],
  ["BLR", "UKR"],
  ["BLZ", "GTM"],
  ["BLZ", "MEX"],
  ["BOL", "BRA"],
  ["BOL", "CHL"],
  ["BOL", "PER"],
  ["BOL", "PRY"],
  ["BRA", "COL"],
  ["BRA", "GUF"],
  ["BRA", "GUY"],
  ["BRA", "PER"],
  ["BRA", "PRY"],
  ["BRA", "SUR"],
  ["BRA", "URY"],
  ["BRA", "VEN"],
  ["BRN", "MYS"],
  ["BTN", "CHN"],
  ["BTN", "IND"],
  ["BWA", "NAM"],
  ["BWA", "ZAF"],
  ["BWA", "ZMB"],
  ["BWA", "ZWE"],
  ["CAF", "CMR"],
  ["CAF", "COD"],
  ["CAF", "COG"],
  ["CAF", "SDN"],
  ["CAF", "SSD"],
  ["CAF", "TCD"],
  ["CAN", "USA"],
  ["CHE", "DEU"],
  ["CHE", "FRA"],
  ["CHE", "ITA"],
  ["CHE", "LIE"],
  ["CHL", "PER"],
  ["CHN", "HKG"],
  ["CHN", "IND"],
  ["CHN", "KAZ"],
  ["CHN", "KGZ"],
  ["CHN", "LAO"],
  ["CHN", "MAC"],
  ["CHN", "MMR"],
  ["CHN", "MNG"],
  ["CHN", "NPL"],
  ["CHN", "PAK"],
  ["CHN", "PRK"],
  ["CHN", "RUS"],
  ["CHN", "TJK"],
  ["CHN", "VNM"],
  ["CIV", "GHA"],
  ["CIV", "GIN"],
  ["CIV", "LBR"],
  ["CIV", "MLI"],
  ["CMR", "COG"],
  ["CMR", "GAB"],
  ["CMR", "GNQ"],
  ["CMR", "NGA"],
  ["CMR", "TCD"],
  ["COD", "COG"],
  ["COD", "RWA"],
  ["COD", "SSD"],
  ["COD", "TZA"],
  ["COD", "UGA"],
  ["COD", "ZMB"],
  ["COG", "GAB"],
  ["COL", "ECU"],
  ["COL", "PAN"],
  ["COL", "PER"],
  ["COL", "VEN"],
  ["CRI", "NIC"],
  ["CRI", "PAN"],
  ["CZE", "DEU"],
  ["CZE", "POL"],
  ["CZE", "SVK"],
  ["DEU", "DNK"],
  ["DEU", "FRA"],
  ["DEU", "LUX"],
  ["DEU", "NLD"],
  ["DEU", "POL"],
  ["DJI", "ERI"],
  ["DJI", "ETH"],
  ["DJI", "SOM"],
  ["DOM", "HTI"],
  ["DZA", "ESH"],
  ["DZA", "LBY"],
  ["DZA", "MAR"],
  ["DZA", "MLI"],
  ["DZA", "MRT"],
  ["DZA", "NER"],
  ["DZA", "TUN"],
  ["ECU", "PER"],
  ["EGY", "ISR"],
  ["EGY", "LBY"],
  ["EGY", "PSE"],
  ["EGY", "SDN"],
  ["ERI", "ETH"],
  ["ERI", "SDN"],
  ["ESH", "MAR"],
  ["ESH", "MRT"],
  ["ESP", "FRA"],
  ["ESP", "GIB"],
  ["ESP", "MAR"],
  ["ESP", "PRT"],
  ["EST", "LVA"],
  ["EST", "RUS"],
  ["ETH", "KEN"],
  ["ETH", "SDN"],
  ["ETH", "SOM"],
  ["ETH", "SSD"],
  ["FIN", "NOR"],
  ["FIN", "RUS"],
  ["FIN", "SWE"],
  ["FRA", "ITA"],
  ["FRA", "LUX"],
  ["FRA", "MCO"],
  ["GAB", "GNQ"],
  ["GBR", "IRL"],
  ["GEO", "RUS"],
  ["GEO", "TUR"],
  ["GHA", "TGO"],
  ["GIN", "GNB"],
  ["GIN", "LBR"],
  ["GIN", "MLI"],
  ["GIN", "SEN"],
  ["GIN", "SLE"],
  ["GMB", "SEN"],
  ["GNB", "SEN"],
  ["GRC", "MKD"],
  ["GRC", "TUR"],
  ["GTM", "HND"],
  ["GTM", "MEX"],
  ["GTM", "SLV"],
  ["GUF", "SUR"],
  ["GUY", "SUR"],
  ["GUY", "VEN"],
  ["HND", "NIC"],
  ["HND", "SLV"],
  ["HRV", "HUN"],
  ["HRV", "MNE"],
  ["HRV", "SRB"],
  ["HRV", "SVN"],
  ["HUN", "ROU"],
  ["HUN", "SRB"],
  ["HUN", "SVK"],
  ["HUN", "SVN"],
  ["HUN", "UKR"],
  ["IDN", "MYS"],
  ["IDN", "PNG"],
  ["IDN", "TLS"],
  ["IND", "MMR"],
  ["IND", "NPL"],
  ["IND", "PAK"],
  ["IRN", "IRQ"],
  ["IRN", "PAK"],
  ["IRN", "TKM"],
  ["IRN", "TUR"],
  ["IRQ", "JOR"],
  ["IRQ", "KWT"],
  ["IRQ", "SAU"],
  ["IRQ", "SYR"],
  ["IRQ", "TUR"],
  ["ISR", "JOR"],
  ["ISR", "LBN"],
  ["ISR", "PSE"],
  ["ISR", "SYR"],
  ["ITA", "SMR"],
  ["ITA", "SVN"],
  ["ITA", "VAT"],
  ["JOR", "PSE"],
  ["JOR", "SAU"],
  ["JOR", "SYR"],
  ["KAZ", "KGZ"],
  ["KAZ", "RUS"],
  ["KAZ", "TKM"],
  ["KAZ", "UZB"],
  ["KEN", "SOM"],
  ["KEN", "SSD"],
  ["KEN", "TZA"],
  ["KEN", "UGA"],
  ["KGZ", "TJK"],
  ["KGZ", "UZB"],
  ["KHM", "LAO"],
  ["KHM", "THA"],
  ["KHM", "VNM"],
  ["KOR", "PRK"],
  ["KWT", "SAU"],
  ["LAO", "MMR"],
  ["LAO", "THA"],
  ["LAO", "VNM"],
  ["LBN", "SYR"],
  ["LBR", "SLE"],
  ["LBY", "NER"],
  ["LBY", "SDN"],
  ["LBY", "TCD"],
  ["LBY", "TUN"],
  ["LSO", "ZAF"],
  ["LTU", "LVA"],
  ["LTU", "POL"],
  ["LTU", "RUS"],
  ["LVA", "RUS"],
  ["MAF", "SXM"],
  ["MDA", "ROU"],
  ["MDA", "UKR"],
  ["MEX", "USA"],
  ["MKD", "SRB"],
  ["MKD", "XKX"],
  ["MLI", "MRT"],
  ["MLI", "NER"],
  ["MLI", "SEN"],
  ["MMR", "THA"],
  ["MNE", "SRB"],
  ["MNE", "XKX"],
  ["MNG", "RUS"],
  ["MOZ", "MWI"],
  ["MOZ", "SWZ"],
  ["MOZ", "TZA"],
  ["MOZ", "ZAF"],
  ["MOZ", "ZMB"],
  ["MOZ", "ZWE"],
  ["MRT", "SEN"],
  ["MWI", "TZA"],
  ["MWI", "ZMB"],
  ["MYS", "THA"],
  ["NAM", "ZAF"],
  ["NAM", "ZMB"],
  ["NER", "NGA"],
  ["NER", "TCD"],
  ["NGA", "TCD"],
  ["NOR", "RUS"],
  ["NOR", "SWE"],
  ["OMN", "SAU"],
  ["OMN", "YEM"],
  ["POL", "RUS"],
  ["POL", "SVK"],
  ["POL", "UKR"],
  ["PRK", "RUS"],
  ["QAT", "SAU"],
  ["ROU", "SRB"],
  ["ROU", "UKR"],
  ["RUS", "UKR"],
  ["RWA", "TZA"],
  ["RWA", "UGA"],
  ["SAU", "YEM"],
  ["SDN", "SSD"],
  ["SDN", "TCD"],
  ["SRB", "XKX"],
  ["SSD", "UGA"],
  ["SVK", "UKR"],
  ["SWZ", "ZAF"],
  ["SYR", "TUR"],
  ["TJK", "UZB"],
  ["TKM", "UZB"],
  ["TZA", "UGA"],
  ["TZA", "ZMB"],
  ["ZAF", "ZWE"],
  ["ZMB", "ZWE"],
];

function pairKey(a: string, b: string): string {
  return a < b ? `${a}|${b}` : `${b}|${a}`;
}

/** Exported for the self-check to assert row counts and shape against, not re-typed. */
export const LAND_BORDER_PAIRS: ReadonlySet<string> = new Set(
  RAW_PAIRS.map(([a, b]) => pairKey(a, b))
);

/** True only for two ISO3 codes that share a real land boundary. */
export function isLandBorder(a: string, b: string): boolean {
  return LAND_BORDER_PAIRS.has(pairKey(a, b));
}
