// UN Comtrade public preview client — trade partners, no API key.
//
// Traps handled (design spec §3.6, confirmed live 2026-08-02):
// - `reporterCode`/`partnerCode` are Comtrade's OWN code space, not plain
//   UN M49. It mostly matches M49 but keeps expired historical codes as
//   separate entries — India is 699 today, but 356 ("India (...1974)",
//   India excluding Sikkim) is a distinct, expired reporter that still sits
//   in the same code range. The fix: a committed static map generated by
//   scripts/atlas/build-comtrade-codes.mjs from Comtrade's own reference
//   lists (Reporters.json, partnerAreas.json) — see lib/atlas/comtrade-codes.ts.
// - The response always has `partnerDesc: null` — partner names come from
//   that same generated map, joined on the numeric partner code.
// - The free preview endpoint caps out around 500 rows with NO paging, and
//   without narrowing params one partner appears many times over (once per
//   `motCode`/mode-of-transport, and again per `partner2Code` re-export
//   breakdown) — confirmed live on France: the unfiltered call maxed out at
//   500 rows and never reached Germany or the USA, its two biggest partners,
//   because they were buried under transport-mode duplicates of smaller
//   partners. Passing `motCode=0&partner2Code=0` on the request itself (not
//   just filtering client-side afterwards) collapses that back to one row
//   per real partner and the big partners show up correctly.
// - The endpoint throttles: a call with no partner filter can return
//   HTTP 429 back-to-back with an identical prior call. Retried once.
import { PARTNER_BY_CODE, REPORTER_CODE_BY_ISO3 } from "../comtrade-codes";
import type { SourceResult, TradePartner, TradeSummary } from "../types";

const REVALIDATE_WEEK = 604800;

const USER_AGENT = "AtlasCountryExplorer/1.0 (https://sushantgundla.com/atlas)";

interface ComtradeRow {
  refYear: number;
  period: string;
  partnerCode: number;
  partner2Code: number;
  primaryValue: number;
  isAggregate: boolean;
}

interface ComtradeResponse {
  count: number;
  data: ComtradeRow[];
}

async function fetchFlow(
  reporterCode: number,
  year: number,
  flow: "X" | "M"
): Promise<ComtradeRow[]> {
  const url = `https://comtradeapi.un.org/public/v1/preview/C/A/HS?reporterCode=${reporterCode}&period=${year}&cmdCode=TOTAL&flowCode=${flow}&motCode=0&partner2Code=0`;
  for (let attempt = 0; attempt < 2; attempt++) {
    const res = await fetch(url, {
      headers: { "User-Agent": USER_AGENT },
      next: { revalidate: REVALIDATE_WEEK },
    });
    if (res.ok) {
      const body = (await res.json()) as ComtradeResponse;
      return body.data ?? [];
    }
    if (res.status !== 429 || attempt === 1) {
      throw new Error(`Comtrade HTTP ${res.status} for reporter ${reporterCode} flow ${flow}`);
    }
    await new Promise((r) => setTimeout(r, 1500));
  }
  return [];
}

function toPartners(rows: ComtradeRow[], year: string): TradePartner[] {
  const real = rows.filter((r) => r.partner2Code === 0 && r.partnerCode !== 0);
  const total = rows.find((r) => r.partnerCode === 0 && r.partner2Code === 0)?.primaryValue ?? null;
  return real
    .sort((a, b) => b.primaryValue - a.primaryValue)
    .map((r) => {
      const partner = PARTNER_BY_CODE[r.partnerCode];
      return {
        iso3: partner?.iso3 ?? null,
        name: partner?.name ?? `Partner ${r.partnerCode}`,
        value: r.primaryValue,
        year,
        share: total ? r.primaryValue / total : null,
      };
    });
}

/**
 * Top export and import partners for one country in the most recent
 * available year. Comtrade's annual data lags, so this walks back from the
 * current year until it finds a year with rows (up to 3 years).
 */
export async function fetchTradeSummary(iso3: string): Promise<SourceResult<TradeSummary>> {
  try {
    const reporterCode = REPORTER_CODE_BY_ISO3[iso3];
    if (reporterCode === undefined) {
      return { ok: false, reason: `${iso3} is not a current UN Comtrade reporter` };
    }

    const currentYear = new Date().getFullYear();
    for (let year = currentYear - 1; year >= currentYear - 4; year--) {
      const [exportRows, importRows] = await Promise.all([
        fetchFlow(reporterCode, year, "X"),
        fetchFlow(reporterCode, year, "M"),
      ]);
      if (exportRows.length > 0 || importRows.length > 0) {
        return {
          ok: true,
          data: {
            reporterIso3: iso3,
            year: String(year),
            exports: toPartners(exportRows, String(year)).slice(0, 15),
            imports: toPartners(importRows, String(year)).slice(0, 15),
          },
        };
      }
    }
    return {
      ok: true,
      data: { reporterIso3: iso3, year: null, exports: [], imports: [] },
    };
  } catch (err) {
    return { ok: false, reason: err instanceof Error ? err.message : String(err) };
  }
}
